# ForestSentinel Configuration

data:
  input_dir: "./data/raw"
  processed_dir: "./data/processed"
  output_dir: "./output"
  sources:
    - name: "Landsat8"
      bands:
        - name: "B2"
          description: "Blue"
        - name: "B3"
          description: "Green"
        - name: "B4"
          description: "Red"
        - name: "B5"
          description: "NIR"
      resolution: 30  # meters

data_sources:
  landsat:
    collection: "LANDSAT/LC08/C02/T1_L2"
    bands: ["SR_B2", "SR_B3", "SR_B4", "SR_B5"]  # Blue, Green, Red, NIR
    
processing:
  cloud_mask: True
  ndvi_threshold: 0.3
  indices: ["NDVI", "EVI"]
  change_detection:
    method: "zscore"
    threshold: -2.0
    window_size: 4  # months

alerting:
  thresholds:
    ndvi_drop: 0.15  # 15% decrease triggers alert


spark:
  master: "local[*]"
  app_name: "ForestSentinel"
  config:
    - key: "spark.executor.memory"
      value: "4g"
    - key: "spark.driver.memory"
      value: "4g"



alerting:
  enabled: true
  email:
    smtp_server: "smtp.example.com"
    sender: "alerts@forestsentinel.com"
    recipients:
      - "admin@example.com"
